### ISSUE TITLE
ModuleNotFoundError: No module named 'BackEnd'

### ISSUE THREAD

**Issue by laidingq** [NimaNzrii/comfyui-photoshop#145]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\comfyui-photoshop\__init__.py", line 21, in <module>
    importlib.import_module("BackEnd")
  File "D:\ComfyUI\miniconda\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'BackEnd'

Successfully built backend
Installing collected packages: backend
Successfully installed backend-0.2.4.1

**Comment by NimaNzrii** [comment]
Oh , i think there are 2 backend.py loading in your comfy
So i just renamed it

Can you update it one more time and test it?

I have tested it and it's kinda wired to get this error

**Comment by laidingq** [comment]
After the update, it still cannot be loaded

**Comment by NimaNzrii** [comment]
Will fix it when got home

Sorry for this bug...

**Comment by NimaNzrii** [comment]
# fixed

Update the node and enjoy 

Thank you for your patience
