### ISSUE TITLE
Error occurred when executing LoraLoader

### ISSUE THREAD

**Issue by denipesto** [NimaNzrii/comfyui-photoshop#152]
Thanks for the great plugin. 
I'm getting an error, I did everything according to the instructions

!!! Exception during processing!!! 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/pinokio/api/comfyui.git/app/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/pinokio/api/comfyui.git/app/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/pinokio/api/comfyui.git/app/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/pinokio/api/comfyui.git/app/nodes.py", line 611, in load_lora
    lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
  File "/pinokio/api/comfyui.git/app/comfy/utils.py", line 14, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
AttributeError: 'NoneType' object has no attribute 'lower

**Comment by tolozine** [comment]
the sam error

**Comment by NimaNzrii** [comment]
Guys can you please send an screenshot of your ComfyUi and find the red or purple node please

**Comment by denipesto** [comment]
@NimaNzrii 
![photo_2024-07-16_21-27-40](https://github.com/user-attachments/assets/79b7e606-7683-4b75-8907-4858db377241)
![photo_2024-07-16_21-12-18](https://github.com/user-attachments/assets/604d5dbf-a473-4d70-b47d-85d6c3f7ab56)

**Comment by TheBlackHacker** [comment]
I've been struggling with this error all day today, finally, I realized I was using symlink to link the lora models to the models/loras folder. This makes comfyui unable to read files in the loras folder.

In my case, I use the **hf_hub_download** function to download lora, and this function will automatically use the symlink instead of downloading the file directly to the destination directory.

**Solved:**
Instead of symlink, I copied the lora model back into the models/loras folder. And all was perfect.
