### ISSUE TITLE
real time issue

### ISSUE THREAD

**Issue by triplediple** [NimaNzrii/comfyui-photoshop#19]
Hi @NimaNzrii, hope you're doing well! : ) 

While trying to use comfyui-photoshop I'm running into the issue that the updates that I'm making on my image are not being reflected on the ComfyUI Photoshop Plugin and neither on ComfUI itself. 

In order to see my updated image I need to save the changes, close everything PS and Comfy and restart everything once again. Is there any solution to get the updates in real time like the ones you're showing on your video? Thanks! 

![imageNotUpdating](https://github.com/NimaNzrii/comfyui-photoshop/assets/168872007/6031124e-3c2d-4f21-92df-91c65054b657)

![imageNotUpdating2](https://github.com/NimaNzrii/comfyui-photoshop/assets/168872007/a381373c-5a52-4907-9cc1-067920a1c937)

I'm getting a report and I'll be posting here soon

**Comment by triplediple** [comment]
Report:

Z:\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-06 15:49:25.675760
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: Z:\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: Z:\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.4 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8191 MB, total RAM 32689 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints Z:\A1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs Z:\A1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae Z:\A1111\stable-diffusion-webui\models/VAE
Adding extra search path loras Z:\A1111\stable-diffusion-webui\models/Lora
Adding extra search path loras Z:\A1111\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models Z:\A1111\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models Z:\A1111\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models Z:\A1111\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings Z:\A1111\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks Z:\A1111\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet Z:\A1111\stable-diffusion-webui\models/ControlNet
Error:
[WinError 1314] A required privilege is not held by the client: 'Z:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'Z:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
Adding Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
[comfyui_controlnet_aux] | INFO -> Using ckpts path: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Loaded ControlNetPreprocessors nodes from Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
Could not load ImpactPack nodes Could not find ImpactPack nodes
Traceback (most recent call last):
  File "Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1866, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

Cannot import Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'
### Loading: ComfyUI-Manager (V2.27)
### ComfyUI Revision: 2162 [565eb6d1] | Released on '2024-05-05'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
🔷 Photoshop node added('127.0.0.1', 45624)
🔷 Photoshop Not Connected
[comfy_mtb] | INFO -> loaded 70 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

[rgthree] Loaded 38 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "Do one thing every day that scares you." - Eleanor Roosevelt


Import times for custom nodes:
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-popup_preview
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds (IMPORT FAILED): Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop
   0.4 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   1.1 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   2.2 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
🔷 Photoshop node added('127.0.0.1', 45641)
🔷 Photoshop Not Connected
FETCH DATA from: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[comfy_mtb] | WARNING -> Found multiple match, we will pick the first Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\upscale_models
['Z:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'Z:\\A1111\\stable-diffusion-webui\\models/ESRGAN', 'Z:\\A1111\\stable-diffusion-webui\\models/RealESRGAN', 'Z:\\A1111\\stable-diffusion-webui\\models/SwinIR']
🔷 Photoshop node added('127.0.0.1', 45649)
🔷 Photoshop Not Connected
🔷 Photoshop node added('127.0.0.1', 45653)
🔷 Photoshop Not Connected
🔷 Photoshop launched('127.0.0.1', 63209)
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
Requested to load SD1ClipModel
Loading 1 new model
Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:345: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load AutoencoderKL
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.67it/s]
Prompt executed in 6.68 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.39it/s]
Prompt executed in 2.62 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
Requested to load SD1ClipModel
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.76it/s]
Prompt executed in 6.04 seconds

**Comment by NimaNzrii** [comment]
Hi try to turn on "Rebder On Changes" check box and test it again.
We never had an issue like this
I would love  to fix it for you

**Comment by triplediple** [comment]
Hi ! Thanks for the reply!  
I tried both with "Render On Changes" ticked, and later also with "Auto Queue" on as well.
But unfortunately it didn't work : ( 


![PSandComfy_OptionOn](https://github.com/NimaNzrii/comfyui-photoshop/assets/168872007/e1aafa1c-5c02-41b2-9353-878e00f22f71)



Report:

Z:\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-06 17:36:21.708672
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: Z:\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: Z:\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.5 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8191 MB, total RAM 32689 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints Z:\A1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs Z:\A1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae Z:\A1111\stable-diffusion-webui\models/VAE
Adding extra search path loras Z:\A1111\stable-diffusion-webui\models/Lora
Adding extra search path loras Z:\A1111\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models Z:\A1111\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models Z:\A1111\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models Z:\A1111\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings Z:\A1111\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks Z:\A1111\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet Z:\A1111\stable-diffusion-webui\models/ControlNet
Error:
[WinError 1314] A required privilege is not held by the client: 'Z:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'Z:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
Adding Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
[comfyui_controlnet_aux] | INFO -> Using ckpts path: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Loaded ControlNetPreprocessors nodes from Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
Could not load ImpactPack nodes Could not find ImpactPack nodes
Traceback (most recent call last):
  File "Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1866, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

Cannot import Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'
### Loading: ComfyUI-Manager (V2.27)
### ComfyUI Revision: 2162 [565eb6d1] | Released on '2024-05-05'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[comfy_mtb] | INFO -> loaded 70 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

[rgthree] Loaded 38 magnificent nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "The best way to predict the future is to create it." - Peter Drucker


Import times for custom nodes:
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-popup_preview
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds (IMPORT FAILED): Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop
   0.4 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.4 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   1.6 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   2.5 seconds: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[comfy_mtb] | WARNING -> Found multiple match, we will pick the first Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\upscale_models
['Z:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'Z:\\A1111\\stable-diffusion-webui\\models/ESRGAN', 'Z:\\A1111\\stable-diffusion-webui\\models/RealESRGAN', 'Z:\\A1111\\stable-diffusion-webui\\models/SwinIR']
🔷 Photoshop node added('127.0.0.1', 40708)
🔷 Photoshop Not Connected
🔷 Photoshop node added('127.0.0.1', 40711)
🔷 Photoshop Not Connected
🔷 Photoshop launched('127.0.0.1', 35155)
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
loaded straight to GPU
Requested to load BaseModel
Loading 1 new model
Requested to load SD1ClipModel
Loading 1 new model
Z:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:345: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load AutoencoderKL
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.14it/s]
Prompt executed in 14.09 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.32it/s]
Prompt executed in 3.67 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.78it/s]
Prompt executed in 3.04 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.86it/s]
Prompt executed in 2.88 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.41it/s]
Prompt executed in 2.51 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.21it/s]
Prompt executed in 2.60 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.38it/s]
Prompt executed in 2.55 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.40it/s]
Prompt executed in 2.53 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.16it/s]
Prompt executed in 2.69 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.19it/s]
Prompt executed in 2.60 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.36it/s]
Prompt executed in 2.58 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.25it/s]
Prompt executed in 2.60 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.22it/s]
Prompt executed in 2.67 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.30it/s]
Prompt executed in 2.60 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.38it/s]
Prompt executed in 2.56 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.30it/s]
Prompt executed in 2.58 seconds

**Comment by triplediple** [comment]
Okay, here's an update. I was tinkering around and notice that the "Photoshop Canvas" output dongle from "Photoshop ComfyUI Plugin" it's not sending the updated output(my PS document with new brush strokes). But if I bring a "Photoshop RemoteConnection" node and take the "Photoshop Canvas" output and plug it to the "image(input)" node/or a image preview. Then things start to work! :) 

Not sure if I was supposed to be doing this since the beginning... but well, in case not, or in case someone is passing through the same issue... here's a screenshot:
![working](https://github.com/NimaNzrii/comfyui-photoshop/assets/168872007/bb614145-5beb-47ac-86fa-7f9ea8ab8120)

**Comment by NimaNzrii** [comment]
Does the positive abd negetive prompt change for you ?

**Comment by triplediple** [comment]
Yes, I think the text is going through(as per screenshot).

![textinpout](https://github.com/NimaNzrii/comfyui-photoshop/assets/168872007/bcc42477-073c-47ef-a9e3-89e6cc2d9946)

 I didn't play a lot with the plugin yet, but for me the the buttom "Send to Layers" is not clickable/not working. Maybe because I installed the plugin manually by extracting the .ccx file to the PS plugins folder. But I'm just mentioning to give as much detail as possible.

**Comment by Ahcool123** [comment]
I am also replacing the new workflow after it appears so it will not update in real time. Same error log. Latest May 10 Plugin Installations

**Comment by Zumarok** [comment]
I'm also having the same issue. It looks like the 'svim' function is not being called in the 'main.js' script when the photoshop canvas changes. I also installed the photoshop addon by manually extracting the .ccx file so I'm not sure if that's the cause or not.

As a temporary fix I changed the definition of the 'K' function in 'main.js' to call 'svim':

> const K = async () => {
  try {
    await svim();
    1 != X || P || ne("queue"), (X = 1), B || (B = 0.1), S.value || (S.value = 1379), await (await x.createFile("config.json", { overwrite: !0 })).write(JSON.stringify({ postive: L.value, negative: f.value, seed: S.value, slider: B, pluginVer: F }));
  } catch (e) {}
};

**Comment by NimaNzrii** [comment]
Sorry how did you get the log file from Photoshop plugin? Did it just appeared as an error?

I just got a bit surprised because it never happened to me
