### ISSUE TITLE
Can´t install depenandat package photoshop-connection on macOS.

### ISSUE THREAD

**Issue by freke1981SWE** [NimaNzrii/comfyui-photoshop#2]
subprocess.run(["./python_embeded/python.exe", "-m", "pip", "install", "photoshop-connection"])

This throws an error that the python.exe can´t be found on macOS. Temporarily solved it by installing the photoshop-connection package manually in venv.

**Comment by QianquanChina** [comment]
> ```
> subprocess.run(["./python_embeded/python.exe", "-m", "pip", "install", "photoshop-connection"])
> ```
> 
> This throws an error that the python.exe can´t be found on macOS. Temporarily solved it by installing the photoshop-connection package manually in venv.

Win10 also has this problem, I installed it manually

**Comment by Chaoses-Ib** [comment]
Manual installation doesn't work for me either. Any ideas?
```python
> python -m pip install photoshop-connection -U
Requirement already satisfied: photoshop-connection in d:\stable-diffusion-webui\venv\lib\site-packages (0.2.0)
Requirement already satisfied: jinja2<3.1.0 in d:\stable-diffusion-webui\venv\lib\site-packages (from photoshop-connection) (3.0.3)
Requirement already satisfied: cryptography<40.0.0,>=39.0.1 in d:\stable-diffusion-webui\venv\lib\site-packages (from photoshop-connection) (39.0.2)
Requirement already satisfied: cffi>=1.12 in d:\stable-diffusion-webui\venv\lib\site-packages (from cryptography<40.0.0,>=39.0.1->photoshop-connection) (1.15.1)
Requirement already satisfied: pycparser in d:\stable-diffusion-webui\venv\lib\site-packages (from cffi>=1.12->cryptography<40.0.0,>=39.0.1->photoshop-connection) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in d:\stable-diffusion-webui\venv\lib\site-packages (from jinja2<3.1.0->photoshop-connection) (2.1.2)
WARNING: You are using pip version 21.2.3; however, version 23.3.2 is available.
You should consider upgrading via the 'D:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip' command.
> python
Python 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from photoshop import PhotoshopConnection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PhotoshopConnection' from 'photoshop' (D:\stable-diffusion-webui\venv\lib\site-packages\photoshop\__init__.py)
```

**Comment by QianquanChina** [comment]
> Manual installation doesn't work for me either. Any ideas?
> 
> ```python
> > python -m pip install photoshop-connection -U
> Requirement already satisfied: photoshop-connection in d:\stable-diffusion-webui\venv\lib\site-packages (0.2.0)
> Requirement already satisfied: jinja2<3.1.0 in d:\stable-diffusion-webui\venv\lib\site-packages (from photoshop-connection) (3.0.3)
> Requirement already satisfied: cryptography<40.0.0,>=39.0.1 in d:\stable-diffusion-webui\venv\lib\site-packages (from photoshop-connection) (39.0.2)
> Requirement already satisfied: cffi>=1.12 in d:\stable-diffusion-webui\venv\lib\site-packages (from cryptography<40.0.0,>=39.0.1->photoshop-connection) (1.15.1)
> Requirement already satisfied: pycparser in d:\stable-diffusion-webui\venv\lib\site-packages (from cffi>=1.12->cryptography<40.0.0,>=39.0.1->photoshop-connection) (2.21)
> Requirement already satisfied: MarkupSafe>=2.0 in d:\stable-diffusion-webui\venv\lib\site-packages (from jinja2<3.1.0->photoshop-connection) (2.1.2)
> WARNING: You are using pip version 21.2.3; however, version 23.3.2 is available.
> You should consider upgrading via the 'D:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip' command.
> > python
> Python 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from photoshop import PhotoshopConnection
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'PhotoshopConnection' from 'photoshop' (D:\stable-diffusion-webui\venv\lib\site-packages\photoshop\__init__.py)
> ```

I have encountered this problem, but I uninstalled the **photoshop** package in my environment and it was fine.
pip uninstall photoshop
pip install photoshop-connection==0.2.0

**Comment by Chaoses-Ib** [comment]
Weird. Uninstalling `photoshop` first still doesn't work. Python's dependency management is really bad...
```python
> python -m pip uninstall photoshop
Found existing installation: photoshop 0.21.9
Uninstalling photoshop-0.21.9:
  Would remove:
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop-0.21.9.dist-info\*
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\*
  Would not remove (might be manually added):
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api.py
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api\networkEventSubscribe.js.j2
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api\networkEventUnsubscribe.js.j2
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api\open.js.j2
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api\sendDocumentInfoToNetworkClient.js.j2
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api\sendDocumentStreamToNetworkClient.js.j2
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api\sendDocumentThumbnailToNetworkClient.js.j2
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api\sendLayerShapeToNetworkClient.js.j2
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\api\sendLayerThumbnailToNetworkClient.js.j2
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\crypto.py
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\photoshop_connection.py
    d:\stable-diffusion-webui\venv\lib\site-packages\photoshop\protocol.py
Proceed (Y/n)? y
  Successfully uninstalled photoshop-0.21.9

> python -m pip install photoshop-connection==0.2.0
Requirement already satisfied: photoshop-connection==0.2.0 in d:\stable-diffusion-webui\venv\lib\site-packages (0.2.0)
Requirement already satisfied: jinja2<3.1.0 in d:\stable-diffusion-webui\venv\lib\site-packages (from photoshop-connection==0.2.0) (3.0.3)
Requirement already satisfied: cryptography<40.0.0,>=39.0.1 in d:\stable-diffusion-webui\venv\lib\site-packages (from photoshop-connection==0.2.0) (39.0.2)
Requirement already satisfied: cffi>=1.12 in d:\stable-diffusion-webui\venv\lib\site-packages (from cryptography<40.0.0,>=39.0.1->photoshop-connection==0.2.0) (1.15.1)
Requirement already satisfied: pycparser in d:\stable-diffusion-webui\venv\lib\site-packages (from cffi>=1.12->cryptography<40.0.0,>=39.0.1->photoshop-connection==0.2.0) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in d:\stable-diffusion-webui\venv\lib\site-packages (from jinja2<3.1.0->photoshop-connection==0.2.0) (2.1.2)
WARNING: You are using pip version 21.2.3; however, version 23.3.2 is available.
You should consider upgrading via the 'D:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip' command.

> python
Python 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from photoshop import PhotoshopConnection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PhotoshopConnection' from 'photoshop' (unknown location)
>>>
```

**Comment by QianquanChina** [comment]
I guess you couldn’t do it before, maybe you installed the photoshop package. HAHAHA
