### ISSUE TITLE
The latest 1.82 is in the PS beta version, and the menu cannot be displayed, how can I deal with it?

### ISSUE THREAD

**Issue by aazj2024** [NimaNzrii/comfyui-photoshop#203]
The latest 1.82 is in the PS beta version, and the menu cannot be displayed, how can I deal with it?

https://github.com/user-attachments/assets/a03f77d8-2aee-441d-99af-353e78a56d80

**Comment by NimaNzrii** [comment]
Can load your video , can you upload it again?

**Comment by aazj2024** [comment]
I don't know why the video upload error, I sent you an email. It works fine in the official version of PS, but in the beta version of PS, the menu cannot be opened




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NimaNzrii/comfyui-photoshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NimaNzrii/comfyui-photoshop] The latest 1.82 is in the PS beta version, and the menu cannot be displayed, how can I deal with it? (Issue #203)





 
Can load your video , can you upload it again?

**Comment by aazj2024** [comment]
https://github.com/user-attachments/assets/97aded90-f492-4e71-b0cf-9391c1802089


https://github.com/user-attachments/assets/055ea03b-84e1-4af4-bf10-19809ed5a31a

**Comment by aazj2024** [comment]
https://github.com/user-attachments/assets/a065942b-dd40-475e-a536-0763ce7000db

**Comment by NimaNzrii** [comment]
Can you please send me the exact beta version you are using? So i can test and fix it for you

And also did you tried to disable all animations and other options in the settings?

**Comment by aazj2024** [comment]
Hello, thank you very much, we have tested 25.12.XXXX all versions are not good, including 25.12.2716, 25.12.2727, 25.12.2735, etc




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NimaNzrii/comfyui-photoshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 晚上7:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NimaNzrii/comfyui-photoshop] The latest 1.82 is in the PS beta version, and the menu cannot be displayed, how can I deal with it? (Issue #203)





 
Can you please send me the exact beta version you are using? So i can test and fix it for you
 
And also did you tried to disable all animations and other options in the settings?

**Comment by naiyansui2023** [comment]
> 我不知道为什么视频上传错误，我给你发了一封电子邮件。在PS正式版中运行良好，但在PS的Beta版本中，菜单无法打开
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "NimaNzrii/comfyui-photoshop" ***@***.***&gt;; 发送时间:&nbsp;2024年8月16日(星期五) 下午4:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [NimaNzrii/comfyui-photoshop] The latest 1.82 is in the PS beta version, and the menu cannot be displayed, how can I deal with it? (Issue #203) Can load your video , can you upload it again? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Me too.

**Comment by Theliel** [comment]
Ok, I think this is the same problem I have. I'll try to describe it better.

The plugin works in principle. However, the menu and options buttons in the bottom bar of the plugin do not work, the render button does. That is, it is not possible to make the specified menus appear when the buttons are pressed.

That is, the menu for selecting the operation mode (in, out, txt...), as well as the menu for entering the prompt, do not become visible when the specified buttons are pressed.

This doesn't happen with the stable version of PS. I can't be sure from which version of PS Beta it happens, but with the most current version, it doesn't work (the beta one)


Log:

[2024-09-14_17-43-55][13644][Info] [general] analyticsTracker_ is being accessed without setting
[2024-09-14_17-43-55][13644][Warn] [general] Please call HostInfoController::instance()->initialize() when the app is initializing.
[2024-09-14_17-43-56][13644][Info] [general] WebView2BrowserVersion:  128.0.2739.79
[2024-09-14_17-43-56][23088][Default] [console] 🔹 Latest Version:  1.9.3
[2024-09-14_17-43-56][23088][Default] [console] Already updated
[2024-09-14_17-43-57][23088][Debug] [general] 
 */var zr,Rt,Cn,ur,en,Fr,fr,Zh=function(){return typeof window...

 [2024-09-14_17-43-57][23088][Error] [general] Uncaught JS Exception: 
/assets/index-B_-tWO9a.js:26:9531
TypeError: Cannot read properties of undefined (reading 'split')
    at cs (/assets/index-B_-tWO9a.js:26:9532)
    at Ct (/assets/index-B_-tWO9a.js:26:5592)
    at Zo.s.init (/assets/index-B_-tWO9a.js:26:15651)
    at i (/assets/index-B_-tWO9a.js:18:35072)
    at Uo (/assets/index-B_-tWO9a.js:18:5129)
    at t.render (/assets/index-B_-tWO9a.js:18:39246)
    at t.render (/assets/index-B_-tWO9a.js:18:27067)
    at No (/assets/index-B_-tWO9a.js:18:2185)
    at e.updateRoot (/assets/index-B_-tWO9a.js:18:31845)
    at h (/assets/index-B_-tWO9a.js:18:15011)

**Comment by Zeilia59** [comment]
I have the same problem, but on the non-beta version of photoshop 2025.

**Comment by saphtea** [comment]
Also experiencing this issue as well on PS 2025 !! Wonderful plugin though, it is kind of everything I could have wanted out of an AI integration with PS being able to put together my own pipelines. It works for now with the separate window dictating a different preset prompt, but I would really love to have the built in menu options you have for it!
