### ISSUE TITLE
I've upgraded to 1.93, but the Out Paint still fails

### ISSUE THREAD

**Issue by aazj2024** [NimaNzrii/comfyui-photoshop#229]
I've upgraded to 1.93, but the Out Paint still fails....
![QQ截图20240902213043](https://github.com/user-attachments/assets/9d24f3f6-b705-41be-84d4-3270152d5da1)
![QQ截图20240902213052](https://github.com/user-attachments/assets/9756892c-c4be-4f7b-b7d6-4d45c3dd073a)

The following information is prompted

# ComfyUI Error Report
## Error Details
- **Node Type:** ACN_AdvancedControlNetApply
- **Exception Type:** TypeError
- **Exception Message:** AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'vae_optional'
## Stack Trace
```
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.0
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.2.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 11810832384
  - **VRAM Free:** 10268868092
  - **Torch VRAM Total:** 301989888
  - **Torch VRAM Free:** 21134844

## Logs
```
2024-09-02 21:28:07,903 - root - INFO - Total VRAM 11264 MB, total RAM 65421 MB
2024-09-02 21:28:07,903 - root - INFO - pytorch version: 2.2.1+cu121
2024-09-02 21:28:07,904 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-02 21:28:07,904 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
2024-09-02 21:28:09,865 - root - INFO - Using pytorch cross attention
2024-09-02 21:28:11,448 - root - INFO - [Prompt Server] web root: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\web
2024-09-02 21:28:15,847 - root - INFO - Total VRAM 11264 MB, total RAM 65421 MB
2024-09-02 21:28:15,847 - root - INFO - pytorch version: 2.2.1+cu121
2024-09-02 21:28:15,849 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-02 21:28:15,849 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
2024-09-02 21:28:31,579 - root - INFO - 
Import times for custom nodes:
2024-09-02 21:28:31,579 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-09-02 21:28:31,579 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-02 21:28:31,579 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyLiterals
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IPAnimate
2024-09-02 21:28:31,580 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
2024-09-02 21:28:31,581 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-09-02 21:28:31,581 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-02 21:28:31,581 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-02 21:28:31,581 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-02 21:28:31,581 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-02 21:28:31,581 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\comfyui-workspace-manager
2024-09-02 21:28:31,581 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
2024-09-02 21:28:31,581 - root - INFO -    0.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-09-02 21:28:31,581 - root - INFO -    0.4 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-02 21:28:31,581 - root - INFO -    1.5 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\comfy_mtb
2024-09-02 21:28:31,581 - root - INFO -    1.6 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-09-02 21:28:31,581 - root - INFO -    2.0 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-09-02 21:28:31,581 - root - INFO -    2.9 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture
2024-09-02 21:28:31,581 - root - INFO -   10.2 seconds: E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-09-02 21:28:31,581 - root - INFO - 
2024-09-02 21:28:31,596 - root - INFO - Starting server

2024-09-02 21:28:31,597 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-02 21:30:09,500 - root - INFO - got prompt
2024-09-02 21:30:09,664 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-09-02 21:30:09,676 - root - INFO - model_type EPS
2024-09-02 21:30:10,782 - root - INFO - Using pytorch attention in VAE
2024-09-02 21:30:10,784 - root - INFO - Using pytorch attention in VAE
2024-09-02 21:30:11,623 - root - INFO - Requested to load SD1ClipModel
2024-09-02 21:30:11,624 - root - INFO - Loading 1 new model
2024-09-02 21:30:11,922 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-09-02 21:30:12,782 - root - ERROR - !!! Exception during processing !!! AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'vae_optional'
2024-09-02 21:30:12,784 - root - ERROR - Traceback (most recent call last):
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'vae_optional'

2024-09-02 21:30:12,785 - root - INFO - Prompt executed in 3.28 seconds
2024-09-02 21:30:25,961 - root - INFO - got prompt
2024-09-02 21:30:26,086 - root - ERROR - !!! Exception during processing !!! AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'vae_optional'
2024-09-02 21:30:26,086 - root - ERROR - Traceback (most recent call last):
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'vae_optional'

2024-09-02 21:30:26,088 - root - INFO - Prompt executed in 0.12 seconds
2024-09-02 21:31:30,880 - root - INFO - got prompt
2024-09-02 21:31:30,906 - root - ERROR - !!! Exception during processing !!! AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'vae_optional'
2024-09-02 21:31:30,907 - root - ERROR - Traceback (most recent call last):
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ new1.93+ps2753+acr16.5\Adobe Photoshop (Beta)\App\Program Files\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'vae_optional'

2024-09-02 21:31:30,908 - root - INFO - Prompt executed in 0.02 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by ToroLing** [comment]
me too

**Comment by NimaNzrii** [comment]
Can you please send me your log file? 
Comfyui terminal log after getting error

**Comment by zj62621** [comment]
Is this problem solved? I have the same problem.

**Comment by LAOLINok2024** [comment]
There is a problem with this out paint. It always fails whenever it is executed, and a dialog box pops up with the following content:
![outpaint](https://github.com/user-attachments/assets/330c8053-2fef-4df1-9287-abfa1c2ef451)
