### ISSUE TITLE
Which model for the IP Adapter?

### ISSUE THREAD

**Issue by noembryo** [NimaNzrii/comfyui-photoshop#28]
First of all, thank you for your work!
Trying to do some out-paint and I get this:
```
* IPAdapterUnifiedLoader 1431:
  - Exception when validating inner node: tuple index out of range
* IPAdapter 1430:
  - Required input is missing: clip_vision
  - Value not in list: model_name: '0' not in ['ioclab_sd15_recolor.safetensors']
  - Value not in list: dtype: '0.7000000000000001' not in ['fp16', 'fp32']
Output will be ignored
Failed to validate prompt for output 1428:
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'timestep_kf'
Traceback (most recent call last):
  File "E:\AI\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "E:\AI\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'timestep_kf'
```
From what I understand, there is at least a missing model there, since your workflow didn't find any.
The `ioclab_sd15_recolor.safetensors` is the only model that it finds if I try to manually load one.
So, what is the model that you are using there?
![error](https://github.com/NimaNzrii/comfyui-photoshop/assets/24675403/af63cf97-b9c2-4cd0-a3fb-ad5737a141a4)
Never used IP adapter until now, but I try to understand what's more is missing after that..

All the other modes work as expected (even the in-paint)
Great plugin!

**Comment by NimaNzrii** [comment]
hi. I'm so sorry for this mistake. i forgot to update the workflow
i changed some settings in the outpointing and it works better  when we are not using ipadapter 
so
please download the workflow again:
https://openart.ai/workflows/spoonbill_hospitable_34/photoshop-in-comfyui/lreWarJbqiYPcDXnD8hh

**Comment by noembryo** [comment]
Unfortunately the error persists..
```Failed to validate prompt for output 1661:
* KSampler 780:
  - Exception when validating inner node: tuple index out of range
Output will be ignored
Failed to validate prompt for output 1428:
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
Requested to load SD1ClipModel
Loading 1 new model
!!! Exception during processing!!! AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'timestep_kf'
Traceback (most recent call last):
  File "E:\AI\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "E:\AI\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: AdvancedControlNetApply.apply_controlnet() got an unexpected keyword argument 'timestep_kf'
```
![error](https://github.com/NimaNzrii/comfyui-photoshop/assets/24675403/1e091312-7b43-4128-b65a-a288e1a66a4b)

**Comment by NimaNzrii** [comment]
Which checkpoint are you using? Are you sure you have downloaded the inpaint controlnet currently? Some times will be corrupted on downloading

**Comment by noembryo** [comment]
Checkpoint: EpicRealismNaturalSinRC1VAE
The in-paint model I downloaded yesterday..
I'll try to re-download it and inform you..

**Comment by noembryo** [comment]
Using the re-downloaded file everything works..
Thank you. 👍
