### ISSUE TITLE
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.

### ISSUE THREAD

**Issue by Pyrrhic7** [NimaNzrii/comfyui-photoshop#29]
I'm getting this error after installing the custom node.  It will not load properly, although the rest of ComyUI will.  This is on a fresh install of the portable version with everything updated.  Any idea how to fix it?:

I:\1_PROGRAMS\COMFYUI_2024>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-10 21:08:49.401099
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: I:\1_PROGRAMS\COMFYUI_2024\python_embeded\python.exe
** Log path: I:\1_PROGRAMS\COMFYUI_2024\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages for 'I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\ComfyUI-Manager'

[ComfyUI-Manager] Startup script completed.
#######################################################################

Prestartup times for custom nodes:
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\rgthree-comfy
   4.9 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24563 MB, total RAM 65459 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 2128 [258dbc06] | Released on '2024-04-14'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 46, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 26, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 4, in <module>
    import ctypes
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 46, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 26, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 4, in <module>
    import ctypes
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
_PS_ An error occurred while running a subprocess: Command '['I:\\1_PROGRAMS\\COMFYUI_2024\\ComfyUI\\custom_nodes\\comfyui-photoshop\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '--upgrade', 'pip']' returned non-zero exit status 1.
Skip I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
[ReActor] - STATUS - Running v0.5.0-b2 in ComfyUI
Torch version: 2.2.2+cu121
No module named 'ultralytics'
Workspace manager - Openning file hash dict
### Loading: Workspace Manager (V1.0.0)
[comfyui_controlnet_aux] | INFO -> Using ckpts path: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[comfy_mtb] | INFO -> loaded 76 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

[rgthree] Loaded 38 magnificent nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "Great minds discuss ideas; average minds discuss events; small minds discuss people." - Eleanor Roosevelt

Import times for custom nodes:
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\image-resize-comfyui
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\sd-ppp
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-popup_preview
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.8 seconds (IMPORT FAILED): I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-photoshop
   1.1 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfyui-reactor-node
   1.3 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\comfy_mtb
   1.5 seconds: I:\1_PROGRAMS\COMFYUI_2024\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to:

**Comment by NimaNzrii** [comment]
What a great log file , thanks, i think the problem should be ob python 11 
So i will work on it today 
This is my priority

**Comment by NimaNzrii** [comment]
hey , try installing Microsoft Redistributable for Visual Studio C++ 2015-2019 
https://aka.ms/vs/17/release/vc_redist.x64.exe 

then restart your device and try it again💖

let m e know if it fixed your issue

**Comment by Pyrrhic7** [comment]
Nope, installed the vc_redist.x64.exe link you provided, restarted, and issue is still there.  Here's the log I'm not getting:

Total VRAM 24563 MB, total RAM 65459 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.30)
### ComfyUI Revision: 2171 [4f63ee99] | Released on '2024-05-10'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 46, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 26, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 4, in <module>
    import ctypes
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 46, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 26, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 4, in <module>
    import ctypes
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
_PS_ An error occurred while running a subprocess: Command '['I:\\1_PROGRAMS\\COMFYUI\\ComfyUI\\custom_nodes\\comfyui-photoshop\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '--upgrade', 'pip']' returned non-zero exit status 1.
Skip I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
[ReActor] - STATUS - Running v0.5.0-b2 in ComfyUI
Torch version: 2.2.2+cu121
No module named 'ultralytics'
Workspace manager - Openning file hash dict
### Loading: Workspace Manager (V1.0.0)

Import times for custom nodes:
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\sd-ppp
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-popup_preview
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\facerestore_cf
   0.2 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.8 seconds (IMPORT FAILED): I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-photoshop
   1.0 seconds: I:\1_PROGRAMS\COMFYUI\ComfyUI\custom_nodes\comfyui-reactor-node

Starting server

To see the GUI go to:

**Comment by NimaNzrii** [comment]
# should be fixed now for everyone ✨

Please update the **Comfyui-Photoshop** node inside you **comfyui manager**

changed the whole method of installation. its more powerful

and let me know if you had any trouble on running it

**Comment by Pyrrhic7** [comment]
Thanks that fixed the install issue!
