### ISSUE TITLE
Import failed Inference core/Photoshop ComfyUI Plugin

### ISSUE THREAD

**Issue by matroxI** [NimaNzrii/comfyui-photoshop#37]
I read other bug reports. So as I understand the whole problem is in ComfyUI-Inference-Core-Nodes.

I completely reinstalled ComfyUi, but the problem remained exactly the same. Is there an option that the workflow will be rewritten without using Inference Core Nodes? I've been trying for a long time to fix the fact that it gives an error, and I've probably tried everything.

-------------

C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-12 12:22:45.401657
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.3 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 65260 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Error:
[WinError 1314] A required privilege is not held by the client: 'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'C:\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to C:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: C:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'
### ComfyUI Revision: 2128 [258dbc06] | Released on '2024-04-14'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 46, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 26, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 4, in <module>
    import ctypes
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 46, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 26, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 4, in <module>
    import ctypes
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
_PS_ An error occurred while running a subprocess: Command '['C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui-photoshop\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '--upgrade', 'pip']' returned non-zero exit status 1.
Skip C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']

Full error log from comfyui_controlnet_aux:
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 15, in <module>
    from . import util
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\util.py", line 8, in <module>
    from .body import BodyResult, Keypoint
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\body.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\projections\__init__.py", line 55, in <module>
    from .. import axes, _docstring
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\axes\__init__.py", line 2, in <module>
    from ._axes import *
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\axes\_axes.py", line 11, in <module>
    import matplotlib.category  # Register category unit converter as side effect.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\category.py", line 14, in <module>
    import dateutil.parser
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\dateutil\parser\__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\dateutil\parser\_parser.py", line 42, in <module>
    import six
ModuleNotFoundError: No module named 'six'

[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because ModuleNotFoundError: No module named 'six'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)
[comfy_mtb] | INFO -> loaded 73 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

[rgthree] Loaded 38 fantastic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.3 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.8 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   1.1 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

**Comment by NimaNzrii** [comment]
# Fixed ✨

Thank you for your report.💖
Please update the **Comfyui-Photoshop** node inside you **comfyui manager**

and let me know if you had any trouble on running it
