### ISSUE TITLE
Connection issues on mac..

### ISSUE THREAD

**Issue by 3170** [NimaNzrii/comfyui-photoshop#52]
Error occurred when executing 🔹Photoshop ComfyUI Plugin:

Heya, I am trying to get it running but having issues.
I'm on mac m1, latest PS, latest ComfyUI via pinokio (this an issue?)

Please help.

Log below.
---

Failed to load directory after 5 attempts. 
 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. 
 🔴 otherwise you can restart your photosop and your plugin to Fix this problem

  File "/Users/DEMON_1_2/pinokio/api/comfyui.git/app/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/DEMON_1_2/pinokio/api/comfyui.git/app/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/DEMON_1_2/pinokio/api/comfyui.git/app/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/DEMON_1_2/pinokio/api/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 33, in PS_Execute
    self.loadConfig()
  File "/Users/DEMON_1_2/pinokio/api/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
    self.loadConfig(retry_count + 1)
  File "/Users/DEMON_1_2/pinokio/api/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
    self.loadConfig(retry_count + 1)
  File "/Users/DEMON_1_2/pinokio/api/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
    self.loadConfig(retry_count + 1)
  [Previous line repeated 1 more time]
  File "/Users/DEMON_1_2/pinokio/api/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 77, in loadConfig
    raise Exception("Failed to load directory after 5 attempts. \n 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. \n 🔴 otherwise you can restart your photosop and your plugin to Fix this problem")

**Comment by huameiwei-vc** [comment]
> 执行Photoshop ComfyUI插件时出错：🔹
> 
> 嘿，我试图让它运行，但有问题。 我在Mac M1上，最新的PS，最新的ComfyUI通过pinokio（这是一个问题？）
> 
>  请帮帮我
> 
> ##  在下面登录。
> 尝试5次后无法加载目录。 请确保您已成功安装并启动Photoshop插件。 🔴否则你可以重新启动你的photosop和你的插件来解决这个问题
> 
> 文件"/Users/DEMON_1_2/pinokio/API/comfyui. git/app/execution. py"，第151行，recursive_execute output_data，output_ui = get_output_data（obj，input_data_all） 文件“/Users/DEMON_1_2/pinokio/API/comfyui.git/app/execution.py”，第81行，在get_output_data中 return_values = map_node_over_list（obj，input_data_all，obj.FUNCTION，allow_interrupt=True） 文件“/Users/DEMON_1_2/pinokio/API/comfyui.git/app/execution.py”，第74行，在map_node_over_list中 结果.append（getattr（obj，func）（**slice_dict（input_data_all，i） 文件“/Users/DEMON_1_2/pinokio/API/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py”，第33行，PS_Execute  self.loadConfig（） 文件“/Users/DEMON_1_2/pinokio/API/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py”，第75行，载入配置 self. loadConfig（retry_count +1） 文件“/Users/DEMON_1_2/pinokio/API/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py”，第75行，载入配置 self. loadConfig（retry_count +1） 文件“/Users/DEMON_1_2/pinokio/API/comfyui.git/app/custom_nodes/comfyui-photoshop/node-Photoshop.py”，第75行，载入配置 self. loadConfig（retry_count +1） [上一行重复1次] 文件"/Users/DEMON_1_2/pinokio/API/comfyui. git/app/custom_nodes/comfyui—photoshop/node—Photoshop. py"，第77行，载入配置 raise Exception（“5次尝试后加载目录失败。\n请确保已成功安装并启动Photoshop插件。\n否则你可以重新启动你的photosop和你的插件来解决这个问题”）

I'm having the same problem.

**Comment by 3170** [comment]
OK, I went the extra-mile to install ComfyUI regularly (the hard way / without pinokio, just by shell) to find out we're still in the same spot. Damn. Thought it could be an ComfyUI/Pinokio issue.

As said: any help appreciated.

!!! Exception during processing!!! Failed to load directory after 5 attempts. 
 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. 
 🔴 otherwise you can restart your photosop and your plugin to Fix this problem
Traceback (most recent call last):
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig
    with open(self.configJson, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig
    with open(self.configJson, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig
    with open(self.configJson, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig
    with open(self.configJson, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig
    with open(self.configJson, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/DEMON_1_2/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DEMON_1_2/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DEMON_1_2/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 33, in PS_Execute
    self.loadConfig()
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
    self.loadConfig(retry_count + 1)
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
    self.loadConfig(retry_count + 1)
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
    self.loadConfig(retry_count + 1)
  [Previous line repeated 1 more time]
  File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 77, in loadConfig
    raise Exception("Failed to load directory after 5 attempts. \n 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. \n 🔴 otherwise you can restart your photosop and your plugin to Fix this problem")
Exception: Failed to load directory after 5 attempts. 
 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. 
 🔴 otherwise you can restart your photosop and your plugin to Fix this problem

**Comment by huameiwei-vc** [comment]
> OK, I went the extra-mile to install ComfyUI regularly (the hard way / without pinokio, just by shell) to find out we're still in the same spot. Damn. Thought it could be an ComfyUI/Pinokio issue.
> 
> As said: any help appreciated.
> 
> !!! Exception during processing!!! Failed to load directory after 5 attempts. 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. 🔴 otherwise you can restart your photosop and your plugin to Fix this problem Traceback (most recent call last): File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig with open(self.configJson, "r") as file: ^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig with open(self.configJson, "r") as file: ^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig with open(self.configJson, "r") as file: ^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig with open(self.configJson, "r") as file: ^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 70, in loadConfig with open(self.configJson, "r") as file: ^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/DEMON_1_2/ComfyUI/execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/DEMON_1_2/ComfyUI/execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/DEMON_1_2/ComfyUI/execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 33, in PS_Execute self.loadConfig() File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig self.loadConfig(retry_count + 1) File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig self.loadConfig(retry_count + 1) File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig self.loadConfig(retry_count + 1) [Previous line repeated 1 more time] File "/Users/DEMON_1_2/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 77, in loadConfig raise Exception("Failed to load directory after 5 attempts. \n 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. \n 🔴 otherwise you can restart your photosop and your plugin to Fix this problem") Exception: Failed to load directory after 5 attempts. 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. 🔴 otherwise you can restart your photosop and your plugin to Fix this problem

Yes, that's what I followed comfyui's instructions to install, it should be the difference in ps between windows and mac.

**Comment by 3170** [comment]
I salute you! This issue is history. Great work on the plugin! Best, E
