### ISSUE TITLE
Error occurred when executing CheckpointLoaderSimple:

### ISSUE THREAD

**Issue by lednevandrey04** [NimaNzrii/comfyui-photoshop#88]
I used your tips on setting up and using the extension. After clicking the render button, I get an error in the ComfyUI window
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

Error occurred when executing CheckpointLoaderSimple:

'NoneType' object has no attribute 'lower'

File "D:\StabilityMatrix\Packages\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\StabilityMatrix\Packages\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\StabilityMatrix\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\StabilityMatrix\Packages\ComfyUI\nodes.py", line 516, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
File "D:\StabilityMatrix\Packages\ComfyUI\comfy\sd.py", line 445, in load_checkpoint_guess_config
sd = comfy.utils.load_torch_file(ckpt_path)
File "D:\StabilityMatrix\Packages\ComfyUI\comfy\utils.py", line 13, in load_torch_file
if ckpt.lower().endswith(".safetensors"):
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

![error](https://github.com/NimaNzrii/comfyui-photoshop/assets/76588218/cd8f5cce-5262-4995-bd7f-eb3aba9598cd)

**Comment by lednevandrey04** [comment]
Failed to validate prompt for output 1157:
* ImageResize+ 1680:3:
  - Value not in list: method: 'True' not in ['stretch', 'keep proportion', 'fill / crop', 'pad']
Output will be ignored
Failed to validate prompt for output 1661:
* CheckpointLoaderSimple 1074:
  - Value not in list: ckpt_name: 'Stable-diffusion\epicrealism_naturalSinRC1VAE.safetensors' not in (list of length 22)
Output will be ignored
Failed to validate prompt for output 1428:
* ImageResize+ 1031:
  - Value not in list: method: 'False' not in ['stretch', 'keep proportion', 'fill / crop', 'pad']
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
!!! Exception during processing!!! 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\StabilityMatrix\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\StabilityMatrix\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\StabilityMatrix\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\StabilityMatrix\Packages\ComfyUI\nodes.py", line 516, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "D:\StabilityMatrix\Packages\ComfyUI\comfy\sd.py", line 445, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
  File "D:\StabilityMatrix\Packages\ComfyUI\comfy\utils.py", line 13, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
AttributeError: 'NoneType' object has no attribute 'lower'

Prompt executed in 0.02 seconds
