### ISSUE TITLE
v1.4 freezes ComfyUI

### ISSUE THREAD

**Issue by noembryo** [NimaNzrii/comfyui-photoshop#94]
https://github.com/NimaNzrii/comfyui-photoshop/assets/24675403/79a63acb-7ee8-43b4-8e19-797ce1ecaa28

What I get is just this:
`_PS_ Node found in workflow: ('127.0.0.1', 51490)`
Just updated the node..

**Comment by NimaNzrii** [comment]
Oh that's strange!
 can you please go to this path comfyui/input

And rename one of your files to PS_canvas.png 

Then refresh your browser page and try it again 

Let me know if it fixed it

**Comment by NimaNzrii** [comment]
Abd if it didn't help please 
1- open your browser 
2- press F12 
3- click on "console" tab
4- add the node abd let it crash
5- then copy the whole log of your console tab

![17181371770094495504837454913756-01](https://github.com/NimaNzrii/comfyui-photoshop/assets/148809650/014281e7-e449-4dec-aa2d-643cd051696c)

**Comment by noembryo** [comment]
It didn't work.. 😞 
The log is
```Failed to load image: /view?filename=PS_canvas.png&subfolder=&type=input&no-cache=1718137366760
img.onerror @ nodestyle.js:52
error (async)
setBackgroundImageContain @ nodestyle.js:51
(anonymous) @ nodestyle.js:62
previewonthenode @ nodestyle.js:61
nodeCreated @ nodestyle.js:150
(anonymous) @ app.js:252
#invokeExtensionsAsync @ app.js:249
ComfyNode @ app.js:1702
createNode @ litegraph.core.js:435
LiteGraph.createNode @ use_everywhere.js:260
select @ litegraph.core.js:11671
(anonymous) @ litegraph.core.js:11985
nodestyle.js:43 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at node.onDrawBackground (http://127.0.0.1:8188/extensions/comfyui-photoshop/nodestyle.js:43:13)
    at LGraphCanvas.drawNodeShape (http://127.0.0.1:8188/lib/litegraph.core.js:9008:18)
    at LGraphCanvas.drawNodeShape (http://127.0.0.1:8188/scripts/app.js:1213:34)
    at LGraphCanvas.drawNodeShape (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/locking.js:84:30)
    at LGraphCanvas.drawNode (http://127.0.0.1:8188/lib/litegraph.core.js:8531:14)
    at LGraphCanvas.drawNode (http://127.0.0.1:8188/extensions/rgthree-comfy/label.js:134:27)
    at LGraphCanvas.drawNode (http://127.0.0.1:8188/extensions/core/snapToGrid.js:88:24)
    at http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:39:43
    at wrapCallInSettingCheck (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:12:13)
    at LGraphCanvas.drawNode (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:39:5)
node.onDrawBackground @ nodestyle.js:43
LGraphCanvas.drawNodeShape @ litegraph.core.js:9008
LGraphCanvas.drawNodeShape @ app.js:1213
LGraphCanvas.drawNodeShape @ locking.js:84
LGraphCanvas.drawNode @ litegraph.core.js:8531
LGraphCanvas.drawNode @ label.js:134
LGraphCanvas.drawNode @ snapToGrid.js:88
(anonymous) @ snapToGrid.js:39
wrapCallInSettingCheck @ snapToGrid.js:12
LGraphCanvas.drawNode @ snapToGrid.js:39
LGraphCanvas.drawNode @ app.js:1304
LGraphCanvas.drawNode @ use_everywhere.js:186
LGraphCanvas.drawFrontCanvas @ litegraph.core.js:7827
LGraphCanvas.draw @ litegraph.core.js:7742
LGraphCanvas.draw @ image_chooser.js:73
renderFrame @ litegraph.core.js:5809
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
requestAnimationFrame (async)
renderFrame @ litegraph.core.js:5814
nodestyle.js:169 
        
        
       GET https://raw.githubusercontent.com/NimaNzrii/comfyui-photoshop/main/PreviewFiles/version.json 404 (Not Found)
checkForNewVersion @ nodestyle.js:169
(anonymous) @ nodestyle.js:219
handleMessage @ connection.js:30
(anonymous) @ connection.js:16
nodestyle.js:201 Error checking for new version: Error: Failed to fetch version information
    at checkForNewVersion (nodestyle.js:171:13)
```

**Comment by noembryo** [comment]
There are stuff missing from the log I posted..
Wait until I find a way to post them all..

**Comment by noembryo** [comment]
OK.
The missing lines were these at the top..
```
GET http://127.0.0.1:8188/view?filename=PS_canvas.png&subfolder=&type=input&no-cache=1718137366760 404 (Not Found)
Failed to load image: /view?filename=PS_canvas.png&subfolder=&type=input&no-cache=1718137366760
```

**Comment by NimaNzrii** [comment]
So it fixed by renaming it?

**Comment by NimaNzrii** [comment]
How did you fixed it , also i really want to get more in touch with you but i cant find anyway to do it-_-

**Comment by noembryo** [comment]
>How did you fixed it

Just renamed the very cleverly named `PS_canvas.png.png` to `PS_canvas.png`.. 🤣 
>  also i really want to get more in touch with you but i cant find anyway to do it-_-

I did fill the form you asked [here ](https://github.com/NimaNzrii/comfyui-photoshop/issues/62#issuecomment-2126255222) with my email but you didn't mail me..
My mail is really easy... noembryo at gmail com..

Unfortunately tomorrow I leave for holidays and I won't be at my PC until July..
But I did post some of my presets [here](https://github.com/NimaNzrii/comfyui-photoshop/issues/87).
I also use the [ComfyUI-Inpaint-CropAndStitch](https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch) nodes for all the presets, by connecting them at the input, so I can work with higher resolution details.
If you're interested I can send you more info and the node template.

BTW from what I saw, you 1.5 workflow still has the `img 2 img (Scribble CN)` [Invert slider node problem](https://github.com/NimaNzrii/comfyui-photoshop/issues/91)..
I'll check the updated plug-in today and if I find anything I post an issue.

**Comment by noembryo** [comment]
Wow!!
From what I can tell, this update is fantastic!!
You added all the features that I wanted! 🥳 
You also changed the output slot name from "output" to "out" and broke all the presets I uploaded.. 😛 
I'll have to add a notice..

Great work! 🍾

**Comment by NimaNzrii** [comment]
😂😂😂 sorry for that , it will not happen again 

I really love your updates , but check the email i want to say smt cool in telegram to u
