### ISSUE TITLE
No module named 'photoshop'

### ISSUE THREAD

**Issue by likwid101** [NimaNzrii/comfyui-photoshop#98]
Editing my issue in hopes that I can get a nugget of information that I can track down the issue. I am running within a docker and pulled down several images and all come up with the same issue that there is no modal "photoshop". I'm assuming that I need to track this down or the fact that import fails for the custom node comfyui-photoshop. Any assistance would be appreciated.

I'll keep my original log below

```
Web extensions folder found at /root/ComfyUI/web/extensions/ComfyLiterals
_PS_ The following packages are missing:
websockets
Files removed: 4
Requirement already satisfied: pip in /usr/lib/python3.11/site-packages (24.0)
Requirement already satisfied: pip in /usr/lib/python3.11/site-packages (24.0)
Requirement already satisfied: setuptools in /usr/lib/python3.11/site-packages (70.0.0)
Requirement already satisfied: websockets in /usr/lib64/python3.11/site-packages (from -r /root/ComfyUI/custom_nodes/comfyui-photoshop/requirements.txt (line 1)) (11.0.3)
_PS_ backend_path /root/ComfyUI/custom_nodes/comfyui-photoshop/Backend.py
Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop-noplugin.py", line 9, in <module>
    from photoshop import PhotoshopConnection
ModuleNotFoundError: No module named 'photoshop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ComfyUI/nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/comfyui-photoshop/__init__.py", line 67, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop-noplugin.py", line 11, in <module>
    subprocess.run(["python", "-m", "pip", "uninstall", "photoshop"], check=True)
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

Cannot import /root/ComfyUI/custom_nodes/comfyui-photoshop module for custom nodes: [Errno 2] No such file or directory: 'python'

Import times for custom nodes:
   0.0 seconds: /root/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Image-Selector
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Crystools-save
   0.0 seconds: /root/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Logic
   0.0 seconds: /root/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /root/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /root/ComfyUI/custom_nodes/sd-dynamic-thresholding
   0.0 seconds: /root/ComfyUI/custom_nodes/comfy-image-saver
   0.0 seconds: /root/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Image-Saver
   0.0 seconds: /root/ComfyUI/custom_nodes/stability-ComfyUI-nodes
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyLiterals
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /root/ComfyUI/custom_nodes/comfyui-portrait-master
   0.0 seconds: /root/ComfyUI/custom_nodes/mikey_nodes
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI_FaceAnalysis
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyMath
   0.1 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.1 seconds: /root/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.1 seconds: /root/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.1 seconds: /root/ComfyUI/custom_nodes/ComfyUI_essentials
   0.1 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.1 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /root/ComfyUI/custom_nodes/rgthree-comfy
   0.1 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /root/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.2 seconds: /root/ComfyUI/custom_nodes/ComfyUI_TensorRT
   0.3 seconds: /root/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.4 seconds: /root/ComfyUI/custom_nodes/ComfyUI-AnimateAnyone-Evolved
   0.5 seconds: /root/ComfyUI/custom_nodes/ComfyUI_smZNodes
   0.6 seconds: /root/ComfyUI/custom_nodes/ComfyUI-layerdiffuse
   0.7 seconds: /root/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.7 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.9 seconds: /root/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.9 seconds: /root/ComfyUI/custom_nodes/comfyui_segment_anything
   1.1 seconds: /root/ComfyUI/custom_nodes/comfyui-reactor-node
   1.5 seconds: /root/ComfyUI/custom_nodes/ComfyUI_InstantID
   1.8 seconds: /root/ComfyUI/custom_nodes/comfy_mtb
   2.8 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Crystools
   4.8 seconds: /root/ComfyUI/custom_nodes/was-node-suite-comfyui
  14.6 seconds (IMPORT FAILED): /root/ComfyUI/custom_nodes/comfyui-photoshop

Starting server
```

**Comment by likwid101** [comment]
Amazing work and you are super responsive to something that is such a gift. Thank you so much!
